FROM node:22-alpine

WORKDIR /usr/src/app

RUN apk update && apk add git curl \
    && rm -rf /var/cache/apk/* \
    && npm install -g @angular/cli

COPY ./source/package.json .
COPY ./source/package-lock.json .

RUN npm ci