name: 🚀 CI & CD 🚀

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - develop
      - main

permissions:
  id-token: write
  contents: read

jobs:
  initial:
    name: 🔸 Initial
    uses: ./.github/workflows/init-vars.yaml

  test:
    name: 🔸 Test
    needs: initial
    if: ${{ needs.initial.outputs.is-test == 'true' }}
    uses: ./.github/workflows/unit-test-angular.yaml
    with:
      aws-region: ${{ needs.initial.outputs.aws-region }}
      aws-role-to-assume: ${{ needs.initial.outputs.aws-role-to-assume }}
      ignore-unit-test-error: ${{ needs.initial.outputs.ignore-unit-test-error == 'true' }}
      test-image-name: ${{ needs.initial.outputs.test-image-name }}
      test-image-tag: ${{ needs.initial.outputs.test-image-tag }}

#  debug-test:
#    name: 🔸 Debug Test
#    needs: [ initial, test ]
#    if: ${{ always() }}
#    runs-on: self-hosted
#    steps:
#      - name: Debug Test
#        run: |
#          echo "Test failed. Please check the logs for details."
#          echo "Test result: ${{ needs.test.result }}"
#          echo "Is Test: ${{ needs.initial.outputs.is-test }}"
#          echo "Is Scan: ${{ needs.initial.outputs.is-scan }}"
#          echo "${{ (needs.initial.outputs.is-scan != 'false') }}"
#          echo "${{ (needs.initial.outputs.ignore-unit-test-error == 'true' || needs.test.result == 'skipped' || needs.test.result == 'success') }}"

  scan:
    name: 🔸 Scan
    needs: [ initial, test ]
    if: ${{ always() &&  (needs.initial.outputs.is-scan != 'false') && (needs.initial.outputs.ignore-unit-test-error == 'true' || needs.test.result == 'skipped' || needs.test.result == 'success') }}
    uses: ./.github/workflows/sonar-scan-angular.yaml
    with:
      ignore-sonar-quality: ${{ needs.initial.outputs.ignore-sonar-quality == 'true' }}
      sonar-project-key: ${{ needs.initial.outputs.sonar-project-key }}
      sonar-host-url: ${{ needs.initial.outputs.sonar-host-url }}
      source-code-directory: ${{ needs.initial.outputs.sonar-scan-source-code-target }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  build-push:
    name: 📦🚀 Build & Push
    needs: [ initial, test, scan ]
    if: ${{ always() && (needs.test.result == 'skipped'|| needs.scan.result == 'success' || needs.initial.outputs.ignore-sonar-quality == 'true') && (needs.test.result != 'failure' ) }}
    uses: ./.github/workflows/build-push.yaml
    with:
      aws-region: ${{ needs.initial.outputs.aws-region }}
      aws-role-to-assume: ${{ needs.initial.outputs.aws-role-to-assume }}
      image-name: ${{ needs.initial.outputs.image-name }}
      image-tag: ${{ needs.initial.outputs.image-tag }}
      build-spec: ${{ needs.initial.outputs.build-spec }}
      build-args: >
        BUILD_ENV=${{ needs.initial.outputs.build-env }}
        BASE_HREF=${{ needs.initial.outputs.path-pattern }}

  deploy:
    name: 🔸 Deploy
    needs: [ initial, build-push ]
    if: ${{ always() }}
    uses: ./.github/workflows/deploy.yaml
    with:
      aws-region: ${{ needs.initial.outputs.aws-region }}
      aws-role-to-assume: ${{ needs.initial.outputs.aws-role-to-assume }}
      image-name: ${{ needs.initial.outputs.image-name }}
      image-tag: ${{ needs.initial.outputs.image-tag }}
      cluster-name: ${{ needs.initial.outputs.cluster-name }}
      service-name: ${{ needs.initial.outputs.service-name }}
      task-definition: ${{ needs.initial.outputs.task-definition }}
      container-name: ${{ needs.initial.outputs.container-name }}


